name: my_app_factory
repository: https://github.com/my_org/my_app_factory

packages:
  - apps/**
  - packages/**

scripts:
  lint:
    run: melos exec -- flutter analyze .
    description: Run `flutter analyze` in all packages.

  bootstrap:
    run: melos bootstrap
    description: Bootstrap all packages.

  clean:
    run: melos clean
    description: Clean all packages.
