name: app_updater
description: A reusable app update checker and force update widget.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^10.1.0
  remote_config:
    path: ../../services/remote_config
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0
