name: deep_linking
description: "Deep link intake and app-pluggable URI parsing."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  app_links: ^7.2.0
  core_utils:
    path: ../../core/core_utils
  flutter:
    sdk: flutter

dev_dependencies:
  app_links_platform_interface: ^2.0.3
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0
