name: analytics
description: A reuseable core package for analytics and logging.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  crash_reporting:
    path: ../crash_reporting
  firebase_analytics: ^12.4.3
  firebase_core: ^4.11.0
  flutter:
    sdk: flutter
  talker_flutter: ^5.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^10.3.0
